title: <p align ="center"> Shivani Khobrekar </p>
logo: /assets/img/photo.jpg
description: 
  <p align="center">
  <a href="/assets/img/Shivani's Resume.pdf">Resume</a>
  <a href="https://www.linkedin.com/in/shivani-khobrekar-787637b8/">Linkedin</a>
  <a href="https://github.com/shivanikhobrekar/">Github</a>

  <br>
  Experienced software developer with 7 years in responsive website creation for tech and services. 
  Innovator integrating APIs, microservices, databases. 
  Lead in high-performance, reusable code. Agile/SDLC understanding.
  Mentor for effective code and growth. 
  Proficient in Ecommerce, Banking, Telecom. Always learning for tech advancement.
  <br>
  </p>



theme: jekyll-theme-minimal
